-- 1. 사용자 프로필 테이블 (Persona 정보 저장)
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nickname TEXT,
  persona TEXT CHECK (persona IN ('silver', 'junior')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 진도 관리 테이블 (각 모듈별 레벨 및 점수 저장)
CREATE TABLE user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  module_name TEXT NOT NULL, -- 'mouse', 'keyboard', 'voice', 'creation'
  level INTEGER NOT NULL,
  max_score INTEGER DEFAULT 0,
  is_completed BOOLEAN DEFAULT FALSE,
  last_played_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, module_name, level)
);

-- RLS (Row Level Security) 설정 - 초기 개발을 위해 모든 권한 허용 (배포 시 수정 필요)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read entries" ON profiles FOR SELECT USING (true);
CREATE POLICY "Allow public insert entries" ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read progress" ON user_progress FOR SELECT USING (true);
CREATE POLICY "Allow public insert progress" ON user_progress FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update progress" ON user_progress FOR UPDATE USING (true);
